### ISSUE TITLE
Did not download all PDF

### ISSUE THREAD

**Issue by SirLupus** [headEx74/Flatex-Documents-Download-Helper#1]
I tried the script and did run into a problem. Tried several times and about 40% of pdf were not downloaded. I figured Chrome was not able to save the whole pdf before the tab get closed, even when saving to ramdisk.

I just deleted line 50   self.driver.close()  and then it worked like a charm and I could download all files. This works fine as flatex always open the same tab, so you don't end up with 100 open tabs :D

**Comment by headEx74** [comment]
Thanks for the hint! Fixed it by removing the line in commit a4812cc , because as you said, Flatex closes the tab by itself when opening the next one. So removing the line `self.driver.close()` (for manual closing the tab) also speeds the process up.
